/*
 * generated by Xtext 2.25.0
 */
package fr.lip6.hupn;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class HUPNRuntimeModule extends AbstractHUPNRuntimeModule {
}
