/*
 * generated by Xtext 2.25.0
 */
package fr.lip6.hupn;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class HUPNStandaloneSetup extends HUPNStandaloneSetupGenerated {

	public static void doSetup() {
		new HUPNStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
