/*
 * generated by Xtext 2.25.0
 */
package fr.lip6.hupn.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class HUPNUiModule extends AbstractHUPNUiModule {

	public HUPNUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
