/*
 * generated by Xtext 2.25.0
 */
package fr.lip6.hupn.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.lip6.hupn.HUPNRuntimeModule;
import fr.lip6.hupn.HUPNStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class HUPNIdeSetup extends HUPNStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new HUPNRuntimeModule(), new HUPNIdeModule()));
	}
	
}
